[package]
name = "ebqn"
version = "0.1.0"
authors = ["Rowan Cannaday <cannadayr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ebqn"
path = "rs_src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0"
once_cell = "1.8.0"
cc_mt = { git = "https://github.com/jrmuizel/cc-mt" }
log = "0.4.14"
syslog = "^4.0"
log-panics = "2.0.0"
